name: Run Data Pipeline

on:

  # Allow to run on demand
  workflow_dispatch: {}

  # Run daily at 9 AM EST
  schedule:
    # 13:00 UTC is 9 AM EST
    - cron: "0 13 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      working-directory: src
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Synchronize datasets
      working-directory: src
      run: |
        python ./update.py

    - name: Upload to Google Cloud Storage
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: finmango-covid-data-v1
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: cp -r output/* gs://school-districts/cases/
        cli: gsutil
